export {
  PROFUNDIDADE_ESCURA_COLORS,
  PROFUNDIDADE_CLARA_COLORS,
  TEMPERATURA_FRIA_COLORS,
  TEMPERATURA_QUENTE_COLORS,
  INTENSIDADE_SUAVE_COLORS,
  INTENSIDADE_BRILHANTE_COLORS,
  TEMPERATURA_FRIA_COLORS2,
  TEMPERATURA_QUENTE_COLORS2,
  PROFUNDIDADE_ESCURA_COLORS2,
  PROFUNDIDADE_CLARA_COLORS2,
  DEFAULT_RAY_COLORS,
  OURO_GRADIENT,
  PRATA_GRADIENT,
} from './maskAnalysisColors'
export type { GradientConfig } from './maskAnalysisColors'
