export { default as PigmentAnalysisStep } from './PigmentAnalysisStep'
export { SliderStepComponent } from './components/SliderStepComponent'
export { ProfundidadeStep } from './components/ProfundidadeStep'
export { GeralSummaryComponent } from './components/GeralSummaryComponent'
export { SliderWithAverageMarker } from './components/SliderWithAverageMarker'
